### ISSUE TITLE
Annotation throws an error

### ISSUE THREAD

**Issue by sdwfrost** [cmccoy/ighutil#1]
Dear @cmccoy 

I've been trying a whole bunch of VDJ assignment software, and I'd like to give ighutil a go. I'm using the 'random1000.fasta' sequences from [this paper](http://www.biomedcentral.com/1471-2105/9/S12/S20), which can be found [here](http://mpsq.biosino.org/ab-origin/ad5.rar).

I can generate a BAM file with vdjalign with no problems:

```
$ vdjalign align-fastq random1000.fastq random1000_ighutil.bam
INFO:vdjalign:aligning
INFO:vdjalign:samtools view -@ 1 -o random1000_ighutil.bam -Sb /tmp/pw-to-bam2VOSZT/samtools-view-fifo
[ig_align] Read 302 references
[ig_align] Read 44 extra references from /tmp/ighdQ3BGQ3/ighd.fasta
[ig_align] Read 13 extra references from /tmp/ighj41GqZT/ighj.fasta
[samopen] SAM header is present: 359 sequences.
[ig_align] Aligned 1000 reads
```

but when it comes to annotation, I get an error:

```
$ ighutil annotate-vdj -i random1000_ighutil.bam -o random1000_ighutil.txt
Exception in thread "main" java.lang.NullPointerException: Missing bq tag.
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
    at io.github.cmccoy.sam.SAMUtils.getAlignedPairs(SAMUtils.java:180)
    at io.github.cmccoy.sam.VDJAnnotator.annotateVDJ(VDJAnnotator.java:39)
    at ighutil.subcommands.annotate_vdj$annotate_read.invoke(annotate_vdj.clj:37)
    at ighutil.subcommands.annotate_vdj$annotate_reads$fn__896.invoke(annotate_vdj.clj:82)
    at clojure.core$map$fn__4245.invoke(core.clj:2559)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$apply.invoke(core.clj:624)
    at ighutil.subcommands.annotate_vdj$annotate_reads.doInvoke(annotate_vdj.clj:82)
    at clojure.lang.RestFn.invoke(RestFn.java:464)
    at ighutil.subcommands.annotate_vdj$annotate_vdj$fn__934.invoke(annotate_vdj.clj:176)
    at clojure.core$map$fn__4245.invoke(core.clj:2559)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$map$fn__4245.invoke(core.clj:2551)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.data.csv$write_csv_STAR_.invoke(csv.clj:118)
    at clojure.data.csv$write_csv.doInvoke(csv.clj:142)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at ighutil.subcommands.annotate_vdj$annotate_vdj.invoke(annotate_vdj.clj:176)
    at clojure.lang.Var.invoke(Var.java:379)
    at cliopatra.command$dispatch.doInvoke(command.clj:96)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at ighutil.main$dispatch_to_subcommand.doInvoke(main.clj:28)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:624)
    at ighutil.main$_main.doInvoke(main.clj:32)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at ighutil.main.main(Unknown Source)
```

Initially, I thought that this was because I first used a FASTA rather than FASTQ, but I get the same error when I convert FASTA to FASTQ using [this script](https://gist.githubusercontent.com/mdshw5/c7cf7a232b27de0d4b31/raw/fasta_to_fastq.py).

Any ideas you may have would be great.

**Comment by darth-donut** [comment]
Same problem here, i'm using a FASTQ file as input too.
